### ISSUE TITLE
Move to stable Rust

### ISSUE THREAD

**Issue by fenhl** [jq-shell/jqsh#2]
It's probably a good idea to get jqsh compiling on stable Rust before adding new features. Easiest way to do that is in 3 stages:
- [x] Get it to compile on the latest nightly
  - [x] Replace deprecated `std` futures (#1)
  - [x] Switch to shaleh/readline (#5)
- [x] Get it to compile on beta
  - [x] Wait for stabilization of `feature(iter_order)` which is planned for Rust 1.5 (upstream rust-lang/rust#27737)
  - [x] Remove [literator](https://github.com/kmcallister/literator) dependency (#7)
  - [x] Remove [linked-hash-map](https://github.com/contain-rs/linked-hash-map) dependency (#8)
- [x] Get it to compile on stable
  - [x] Wait for stabilization of `feature(iter_order)` in Rust 1.5
- [x] Update Travis CI config (#10)
